### ISSUE TITLE
【已解决】所有功能无法使用

### ISSUE THREAD

**Issue by tangyao531** [ZiuChen/NO-FLASH-Upload#14]
### Bug 描述

*![image](https://user-images.githubusercontent.com/96708243/159437066-b6cafb7d-aa70-4a43-a80f-f2ee5a3cda9a.png)加粗、斜体、上传附件等鼠标移上去都是禁止操作的图标，下方文字输入后无法删除*

### 你预期的样子是？

*这应该都可以用吧*

### 脚本的版本
`右上角下拉菜单/检查更新`

*2.0.20*

### 浏览器及版本号
`一般位于设置/关于`

*Chrome 99.0.4844.82*

### 最小成本的复现步骤
`请告诉我们，如何最快的复现该 bug`

- 步骤一：使用插件打开课程平台提交页面
- 步骤二：鼠标移到那些图标上显示无法操作的图标
- 步骤三：微软win11自带输入法在提交框打字无法删除

**Comment by ZiuChen** [comment]
* 请问你的Tampermonkey版本是多少呢？可以`右键拓展 -> 管理拓展`查看，是否是最新的4.15
* 麻烦按一下F12，切换到Console卡片，到编辑器输入文字时看一下控制台是否有报错
    * 如果有报错，请尽量截完整，或者导出完整的控制台日志

![image](https://user-images.githubusercontent.com/64892985/159438385-c9f659d8-694c-4173-9c5b-fea134d5cc12.png)

![image](https://user-images.githubusercontent.com/64892985/159438634-1ff04ce9-5daa-49e5-a06c-9c4de311fdfb.png)

**Comment by tangyao531** [comment]
油猴版本4.13
连不上谷歌服务器，从edge里面复制过去的，没发现没有自动更新功能。
升级到4.15后所有功能可以正常使用，但扩展程序中出现错误信息。

***@***.***

发件人: ***@***.***>
发送时间: 2022年3月22日 16:27
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ZiuChen/NO-FLASH-Upload] 所有功能无法使用 (Issue #14)


  *   请问你的Tampermonkey版本是多少呢？可以右键拓展 -> 管理拓展查看，是否是最新的4.15
  *   麻烦按一下F12，切换到Console卡片，到编辑器输入文字时看一下控制台是否有报错
     *   如果有报错，请尽量截完整，或者导出完整的控制台日志

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F64892985%2F159438385-c9f659d8-694c-4173-9c5b-fea134d5cc12.png&data=04%7C01%7C%7C9bc9589a9a3541cd1eb008da0bddcef4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637835344535488227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=U6UARyHE5zmEOR07eavmWqth%2BrTUFiB2H%2Bl8crS1kh0%3D&reserved=0>

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F64892985%2F159438634-1ff04ce9-5daa-49e5-a06c-9c4de311fdfb.png&data=04%7C01%7C%7C9bc9589a9a3541cd1eb008da0bddcef4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637835344535488227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gD44EfU7xRuqoDsUnl8uG7hrRsVZIBeGjBeBBEEWf%2F8%3D&reserved=0>

―

**Comment by ZiuChen** [comment]
> 油猴版本4.13
连不上谷歌服务器，从edge里面复制过去的，没发现没有自动更新功能。

这个坑之前我也踩了，最终才定位是脚本管理器的问题
原因是：脚本依赖的`Immer`库在`4.13`版本的游猴中需要加载额外模块才能正常启用。

> 升级到4.15后所有功能可以正常使用，但扩展程序中出现错误信息。

拓展程序中错误信息的问题在未来会着手解决

更新到最新版之后能正常用就好 ;D

**Comment by tangyao531** [comment]
谢谢

________________________________
发件人: ZiuChen ***@***.***>
发送时间: Tuesday, March 22, 2022 4:57:57 PM
收件人: ZiuChen/NO-FLASH-Upload ***@***.***>
抄送: tangyao531 ***@***.***>; Author ***@***.***>
主题: Re: [ZiuChen/NO-FLASH-Upload] 所有功能无法使用 (Issue #14)


油猴版本4.13
连不上谷歌服务器，从edge里面复制过去的，没发现没有自动更新功能。

这个坑之前我也踩了，最终才定位是脚本管理器的问题
原因是：脚本依赖的Immer库在4.13版本的游猴中需要加载额外模块才能正常启用。

升级到4.15后所有功能可以正常使用，但扩展程序中出现错误信息。

拓展程序中错误信息的问题在未来会着手解决

更新到最新版之后能正常用就好 ;D

―
