### ISSUE TITLE
课程列表板块 nodata

### ISSUE THREAD

**Issue by Dakai1020** [ZiuChen/NO-FLASH-Upload#16]
![image](https://user-images.githubusercontent.com/80706934/160227460-8159469f-7b63-4d16-957c-23cc55eaf995.png)

**Comment by Dakai1020** [comment]
sorry,再刷新一下就可以了

**Comment by ZiuChen** [comment]
作业列表和课程列表同时请求数据时，就会导致课程列表拿不到数据。
这个我后面研究一下怎么修
