### ISSUE TITLE
建议更换更新脚本的链接

### ISSUE THREAD

**Issue by 1889737514** [ZiuChen/NO-FLASH-Upload#19]
### 问题描述

gitee这个鶸智平台连拉取raw的脚本文件都要求你登录，建议换成其他cdn

### 脚本的版本
2.3.4-2.3.8

### 浏览器及版本号
Firefox 104.0.2，Violentmonkey 2.13.0

### 最小成本的复现步骤

- 步骤一：退出gitee登录
- 步骤二：安装版本2.3.4，进入课程平台后右上角提示有更新版本2.3.8，点击更新
- 步骤三：点击该提示框，弹出gitee登录界面

**Comment by 1889737514** [comment]
另附：violentmonkey的检查更新功能无效（显示无更新），应该也是被gitee这个鶸智登录挡住了

**Comment by ZiuChen** [comment]
感谢反馈，近期会将同步的链接迁移到自己的web服务上。

**Comment by ZiuChen** [comment]
已更新`v2.3.9`版本，替换了Gitee的更新链接，把更新服务迁移到了自己的服务器上，欢迎更新体验😉
