### ISSUE TITLE
无法显示主界面

### ISSUE THREAD

**Issue by 1889737514** [ZiuChen/NO-FLASH-Upload#20]
### Bug 描述

如标题，脚本的主页面不会显示，显示的是课程平台默认的主界面。

### 脚本的版本
`右上角下拉菜单/检查更新`

2.3.9

### 浏览器及版本号
`一般位于设置/关于`

Firefox 106.0.1
Edge 106.0.1370.52
ViolentMonkey 2.13.3

**Comment by ZiuChen** [comment]
不好意思，没能复现你的问题
此脚本支持的运行平台是Tampermonkey并没有对ViolentMonkey做适配
可以尝试一下在Tampermonkey中，脚本是否能正确运行

**Comment by 1889737514** [comment]
测试了一下，tampermonkey确实可以正常运行。
但是此前violentmonkey也能正常运行，但最近突然就运行不了了，如果您有精力的话希望能看一下是什么原因（主要是我脚本都在violentmonkey上，迁移不太方便）

**Comment by 1889737514** [comment]
刚测试了一下，violentmonkey2.3.2版本也能正常运行，但2.3.3版本就不能运行了

**Comment by ZiuChen** [comment]
我检查了一下，目前暴力猴最新的稳定版本是[v2.13.2](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.2)
可以尝试更新到最新版，脚本能否正确运行

**Comment by ZiuChen** [comment]
如果脚本仍然无法正确运行，可以在课程平台首页唤出devTool（按下F12）
检查控制台的报错日志，并将完整截图贴出

**Comment by 1889737514** [comment]
写错了，最新版是2.13.3，不能运行，而2.13.2可以运行
控制台报错如下：
![图片](https://user-images.githubusercontent.com/31409265/197538687-57af5659-aca2-49db-83fd-fa162a557ed5.png)
（另：另一个应该也是您在维护的脚本也有报错，报错截图如下）
![图片](https://user-images.githubusercontent.com/31409265/197539285-8ac66799-0eb4-48b3-99b8-df7a4b03ac24.png)
![图片](https://user-images.githubusercontent.com/31409265/197539006-b7066149-6e8a-42a4-ac89-94d0c1d6bb36.png)

**Comment by ZiuChen** [comment]
我复现了你的情况，但是并没有找到具体应该怎么解决这个问题

这个错误似乎是从暴力猴调用`injected-web.js`将脚本插入到网页中时发生的：

- 我尝试用暴力猴最近的beta版本，即`2.13.3.2`运行脚本，仍然无法运行且报的是另一个错误
- 我到官方仓库检查了`2.13.2`到`2.13.3`相关文件的[改动](https://github.com/violentmonkey/violentmonkey/compare/v2.13.2...v2.13.3)，但仍然没有头绪

脚本从发布之初就没有对暴力猴做可用性测试，我未来也没有精力为暴力猴做特殊适配
也许你可以临时禁用暴力猴的更新，使用旧版暴力猴继续使用脚本 或者单独为此脚本安装Tampermonkey
如果你使用暴力猴运行脚本的需求十分迫切，也许可以向暴力猴提交Issue，这是他们的官方仓库：[violentmonkey](https://github.com/violentmonkey/violentmonkey)

希望我的回答能帮到你

**Comment by 1889737514** [comment]
那也没办法了，装个tampermonkey用着先
辛苦大佬帮忙看了
